### PR TITLE
Adding new pool

### PR DESCRIPTION
**Pull request by Pandapool-io**
Good day,

we are a mining pool - pandapool.io
We would like to be added to your site
Can you please advice how is that possible? 

Best wishes,
the Pandapool team

### CODE REVIEW

**Comment by ellaismer** [comment]
You've sent the wrong PR. But anyway, I'll add the pool to pool list.

**Comment by ellaismer** [comment]
Hmm your pool does not support Ellaism as far as I know. Can you get me the link?

**Comment by Pandapool-io** [comment]
Hi,

thank you for your answer back!
Here is the link to the instruction -
https://pandapool.io/info/howtostart/ethash/19
Also you can see the logo on our main page



Best,
the Pandapool team

2018-02-06 17:32 GMT+03:00 ellaismer <notifications@github.com>:

**Comment by ellaismer** [comment]
Okay. I added it to the pool list.

**Comment by Pandapool-io** [comment]
Hello again!

Thank you for adding our pool!
I have one more question - we also created GUI miner, is there any section
you can add it as well?
Also would like to confirm, are you announcing about new pools that support
your coin in Twitter or Reddit, for instance?

All the best,
the Pandapool Team

2018-02-07 11:50 GMT+03:00 ellaismer <notifications@github.com>:

**Pull request closed without merging**
