### PR TITLE
pool update

### PR DESCRIPTION
**Pull request by riddlez666**

### CODE REVIEW

**Review by ellaismer — CHANGES_REQUESTED** [review]
Do you mind to still call this Minethis? Just want to keep this in sync with Chirs (http://minerpool.net/pools/ellaism/) so we don't create additional confusions.

**Comment by riddlez666** [comment]
He should have updated that :|     Ive messaged him to change yours to Ellaism Core and mine to Ellaism.io changes can still be merged. ive turned off anything to do with minethis

**Comment by riddlez666** [comment]
...

**Comment by ellaismer** [comment]
I'll merge this and  capitalize the name "Ellaism IO" to keep it aligned better with other pool names. Thanks!

**Pull request merged**
